<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_562f6c2d5ff7b',
    'title' => 'Öppettider',
    'fields' => array (
        array (
            'key' => 'field_562f6c3d567e7',
            'label' => 'Måndag',
            'name' => 'monday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f701da1c88',
            'label' => ' ',
            'name' => 'monday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f762bca151',
            'label' => 'Tisdag',
            'name' => 'tuesday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f7638ca152',
            'label' => ' ',
            'name' => 'tuesday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f76a084ca5',
            'label' => 'Onsdag',
            'name' => 'wednesday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f76a784ca6',
            'label' => ' ',
            'name' => 'wednesday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f794193f17',
            'label' => 'Torsdag',
            'name' => 'thursday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f795993f18',
            'label' => ' ',
            'name' => 'thursday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f79c9b587a',
            'label' => 'Fredag',
            'name' => 'friday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f79d0b587b',
            'label' => ' ',
            'name' => 'friday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f79f7b587d',
            'label' => 'Lördag',
            'name' => 'saturday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f79ecb587c',
            'label' => ' ',
            'name' => 'saturday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f7a0db587f',
            'label' => 'Söndag',
            'name' => 'sunday-open',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM), lämna tomt för om det är stängt',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Öppnar',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f7a06b587e',
            'label' => ' ',
            'name' => 'sunday-close',
            'type' => 'text',
            'instructions' => 'Klockslag (format: HH:MM)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'HH:MM',
            'prepend' => 'Stänger',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_562f7a4880b3d',
            'label' => 'Avvikande öppettider',
            'name' => 'abnormal-opening-hours',
            'type' => 'repeater',
            'instructions' => 'Här kan du lägga till avvikande öppettider.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Lägg till rad',
            'sub_fields' => array (
                array (
                    'key' => 'field_562f7a8c80b3e',
                    'label' => 'Datum',
                    'name' => 'date',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                array (
                    'key' => 'field_562f7af680b41',
                    'label' => 'Stängt',
                    'name' => 'stangt',
                    'type' => 'checkbox',
                    'instructions' => 'Är det stängt den valda dagen?',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'closed' => 'Stängt',
                    ),
                    'default_value' => array (
                        '' => '',
                    ),
                    'layout' => 'horizontal',
                ),
                array (
                    'key' => 'field_562f7ac380b3f',
                    'label' => 'Öppnar',
                    'name' => 'open',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_562f7af680b41',
                                'operator' => '!=',
                                'value' => 'closed',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'HH:MM',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_562f7ae180b40',
                    'label' => 'Stänger',
                    'name' => 'close',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_562f7af680b41',
                                'operator' => '!=',
                                'value' => 'closed',
                            ),
                        ),
                    ),
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'HH:MM',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'hbginherithours',
            ),
        ),
    ),
    'menu_order' => 10,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'field',
    'hide_on_screen' => array (
        0 => 'permalink',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'comments',
        4 => 'slug',
        5 => 'featured_image',
        6 => 'categories',
        7 => 'tags',
    ),
));

endif;